site_name: Reinforcement Learning Crashcourse
site_url: https://finger-bone.github.io/rl-crashcourse/
site_description: Reinfrocement Learning with Gym and PyTorch

theme:
  name: lux
  font:
    text: Inter
    code: Fira Code

docs_dir: notes

nav:
- RNN: task1.md
- Attention: task2.md
- Transformer: task3.md

extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  mdx_math:
    enable_dollar_delimiter: true
