[project]
name = "xun-fei-datawhale-translation"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.11,<3.12"
pytorch = ">=2.3.1,<2.4"
numpy = ">=2.0.0,<2.1"
notebook = ">=7.2.1,<7.3"
jupyter = ">=1.0.0,<1.1"
plotly = ">=5.22.0,<5.23"
seaborn = ">=0.13.2,<0.14"
torchvision = ">=0.18.1,<0.19"
transformers = ">=4.41.2,<4.42"

